config/routes.rb
Rails.application.routes.draw do
  get 'oauths/oauth'

  get 'oauths/callback'

	resources :cards do
		collection do
			post 'check'
		end
	end
	resources :users, only: [:new, :create, :edit, :update]
	resources :sessions, only: [:new, :create, :destroy]
	root 'cards#random'
	get 'static_pages/home'
	get '/sign_up', to: 'users#new', as: :sign_up
	get '/log_in', to: 'sessions#new', as: :log_in
	delete '/log_out', to: 'sessions#destroy', as: :log_out

  #Oauth
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/card.rb
class Card < ApplicationRecord
	belongs_to :user
	validates :user_id, :presence => true
	validates :original_text, presence: true, uniqueness: true, length: { minimum: 2 }
	validates :translated_text, presence: true, length: { minimum: 2 }
	validate :same_words?

	scope :expired, -> { where('review_date <= ?', Date.today) }
	scope :random, -> { order('RANDOM()') }

	before_create do
		self.review_date = Date.today
	end


	def move_review_date
		self.review_date = Date.today + 3.days
		self.save
	end

	def check_translation(answer)
		answer.to_s.strip.downcase == self.original_text.to_s.strip.downcase
	end

	private
	def same_words?
		if (self.original_text.to_s.strip.downcase == self.translated_text.to_s.strip.downcase)
			errors.add(:original_text, "слова должны отличаться")
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  has_many :authentications, dependent: :destroy
  has_many :cards, dependent: :destroy
  accepts_nested_attributes_for :authentications

  validates :password, length: { minimum: 3 }, confirmation: true
  validates :email, length: { minimum: 8 }, uniqueness: true, email_format: { message: 'has invalid format' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_login

  def index
  end

  private

  def not_authenticated
    flash[:warning] = 'Вам нужно войти на сайт для просмотра этой страницы'
    redirect_to log_in_path
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	before_action :get_params
	skip_before_action :get_params, only: [:new, :create, :index, :random, :check]
	def index
		@cards = current_user.cards.all
	end

	def random
		@card = current_user.cards.expired.random.first
	end

	def new
		@card = current_user.cards.new
	end

	def edit
	end

	def create
		@card = current_user.cards.create(card_params)
		if @card.persisted?
			flash[:success] = 'Карточка создана'
			redirect_to @card
		else
			flash[:danger] = 'Ошибка при создании карты'
			render 'new'
		end
	end

	def update
		if @card.update(card_params)
			flash[:success] = 'Карточка обновлена'
			redirect_to @card
		else
			flash[:danger] = 'Ошибка при обновлении карты'
			render 'edit'
		end
	end

	def show
	end

	def destroy
		if @card.destroy
			flash[:success] = 'Карточка удалена'
		else
			flash[:warning] = 'Не удалось удалить карточку'
		end
		redirect_to cards_path

	end

	def check
		@card = Card.find(params[:check][:id])
		answer = params[:check][:answer]
		if @card.check_translation(answer)
			@card.move_review_date
			flash[:success] = "Правильный ответ! Следующая проверка: " + @card.review_date.to_s
		else
			flash[:danger] = "Вы неправильно перевели предыдущую карточку!"
		end
		redirect_to root_path
	end

	private
	def get_params
		@card = Card.find(params[:id])
	end

	def card_params
		params.require(:card).permit(:original_text, :translated_text, :user_id)
	end
end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
  skip_before_action :require_login

    # sends the user on a trip to the provider,
    # and after authorizing there back to the callback url.
    def oauth
      login_at(auth_params[:provider])
    end

    def callback
      provider = auth_params[:provider]
      if @user = login_from(provider)
        flash[:success] = "Logged in from #{provider.titleize}!"
        redirect_to root_path
      else
        begin
          @user = create_from(provider)
          # NOTE: this is the place to add '@user.activate!' if you are using user_activation submodule

          reset_session # protect from session fixation attack
          auto_login(@user)
          flash[:success] = "Logged in from #{provider.titleize}!"
          redirect_to root_path
        rescue
          flash.now[:warning] = "Failed to login from #{provider.titleize}!"
          redirect_to root_path
        end
      end
    end

    #example for Rails 4: add private method below and use "auth_params[:provider]" in place of
    #"params[:provider] above.

    private
    def auth_params
      params.permit(:code, :provider, :oauth_token, :oauth_verifier)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_action :require_login, except: [:destroy]
	def new
	end

	def create
		if login(session_params[:email], session_params[:password], session_params[:remember_me])
			flash[:success] = 'С возвращением!'
			redirect_back_or_to root_path
		else
			flash.now[:warning] = 'Неправильный email или пароль'
			render 'new'
		end
	end

	def destroy
		logout
		flash[:success] = 'До свидания!'
		redirect_to log_in_path
	end

	private

  def session_params
    params.permit(:email, :password, :remember_me)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
    def new
        @user = User.new
    end

    def edit
      @user = User.find(params[:id])
  	end

    def create
        @user = User.create(user_params)
        if @user.persisted?
            login(user_params[:email], user_params[:password])
            flash[:success] = 'Вы успешно зарегистрировались'
			      redirect_to root_path
        else
            render 'new'
        end
    end

    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        flash[:success] = 'Профиль обновлен'
        redirect_to edit_user_path(@user)
      else
        flash[:danger] = 'Ошибка при обновлении профиля'
        render 'edit'
      end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation, :id)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_card.html.erb
<div class="card">
            <p><%= I18n.localize(card.review_date.to_date, :format => :myformat) %></p>
            <p><strong><%= card.original_text %></strong> |
            <%= card.translated_text %></p>
            <p><%= link_to 'изменить', edit_card_path(card) %></p>
        </div>

app/views/cards/edit.html.erb
<h1 class="text-center">Изменить карточку</h1>
<%= render partial: 'flashes' %>
<div class="row">
<div class="col-md-6 col-md-offset-3">
<%= simple_form_for @card do |f| %>
  <%= f.input :original_text, label: 'Слово на английском', error: 'Поле обязательно к заполнению' %>
  <%= f.input :translated_text, label: 'Перевод слова на русский', error: 'Поле обязательно к заполнению' %>
  <%= f.submit 'Изменить' %>
  <%= link_to 'удалить', card_path(@card), class: 'link_remove',
              method: :delete,
              data: { confirm: 'Вы действительно хотите удалить карточку?' } %>
<% end %>
</div>
</div>

app/views/cards/index.html.erb
<div class="row">
	<div class="col-md-12">
		<h1 class="text-center">Все карточки</h1>
	</div>
	<div class="col-md-4 col-md-offset-4">
		<div class="text-center">
			<%= render partial: 'flashes' %>
			<%= render @cards %>
		</div>
	</div>
</div>

app/views/cards/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="text-center">
      <h1 class="text-center">Добавить карточку</h1>
    </div>
    <%= render partial: 'flashes' %>
    <%= simple_form_for @card do |f| %>
    <%= f.input :original_text, label: 'Слово на английском', error: 'Поле обязательно к заполнению' %>
    <%= f.input :translated_text, label: 'Перевод слова на русский', error: 'Поле обязательно к заполнению' %>
    <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
    <%= f.submit 'Создать' %>
    <% end %>
  </div>
</div>

app/views/cards/random.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="text-center">
      <%= render partial: 'flashes' %>
      <% if @card %>
      <h1>Как перевести</h1>
      <div class="card">
        <%= @card.translated_text %>
      </div>
    </div>
    <%= simple_form_for(:check, :url => check_cards_path) do |f| %>
    <%= f.input :answer, label: false, placeholder: 'Ваш перевод', error: 'Поле обязательно к заполнению' %>
    <%= f.hidden_field :id, value: @card.id %>
    <%= f.submit 'Проверить' %>
    <% end %>
    <% else %>
    <h1>Вы запомнили все карточки на сегодня</h1>
    <% end %>
  </div>
</div>
</div>

app/views/cards/show.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<div class="text-center">
			<%= render partial: 'flashes' %>
			<%= render partial: 'card', locals: {card: @card } %>
			<%= link_to 'Все карточки', controller: 'cards' %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flashcards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Флэшкарточкер', root_path, class: 'navbar-brand'  %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% if current_user %>
            <li><%= link_to 'Все карточки', cards_path %></li>
            <li><%= link_to 'Добавить карточку', new_card_path %></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
            <li><span><%= current_user.email %></span></li>
            <li><%= link_to 'Выход', log_out_path, method: :delete %></li>
            <li><%= link_to 'Профиль', edit_user_path(current_user) %></li>
            <% else %>
            <li><%= link_to 'Вход', log_in_path %></li>
            <li><%= link_to 'Регистрация', sign_up_path %></li>
            <% end %>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li> -->
      </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
     <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/oauths/callback.html.erb
<h1>Oauths#callback</h1>
<p>Find me in app/views/oauths/callback.html.erb</p>

app/views/oauths/oauth.html.erb
<h1>Oauths#oauth</h1>
<p>Find me in app/views/oauths/oauth.html.erb</p>

app/views/static_pages/home.html.erb
      <div class="page-header">
        <h1>Первый в мире удобный менеджер флеш-карточек. Именно так.</h1>
      </div>

app/views/users/_flashes.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>

app/views/users/edit.html.erb
<h1 class="text-center">Профиль</h1>
<%= render partial: 'flashes' %>
<div class="row">
<div class="col-md-6 col-md-offset-3">
<%= simple_form_for @user do |f| %>
  <%= f.input :email, label: 'Эл.почта', error: 'Поле обязательно к заполнению' %>
  <%= f.input :password, label: 'Пароль', error: 'Поле обязательно к заполнению' %>
  <%= f.submit 'Изменить' %>
  <% end %>
</div>
</div>

app/views/users/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1 class="text-center">Регистрация</h1>
		<%= render partial: 'flashes' %>
		<%= simple_form_for @user do |f| %>
		<%= f.input :email, label: 'Ваш эл.адрес', error: 'Поле обязательно к заполнению' %>
		<%= f.input :password, label: 'Пароль', error: 'Поле обязательно к заполнению' %>
		<%= f.input :password_confirmation, label: 'Подтверждение пароля', error: 'Поле обязательно к заполнению' %>
		<%= f.submit 'Зарегистрироваться' %>
		<% end %>
	</div>
</div>